# http://www.appveyor.com/docs/appveyor-yml

clone_depth: 10

environment:
  matrix:
    - nodejs_version: 6
    - nodejs_version: 7

platform:
  - x86
  - x64

matrix:
  fast_finish: true

version: "{build}"
build: off
deploy: off

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - ps: Copy-Item .env.example .env
  - IF "%platform%" == "x64" CALL "%VS140COMNTOOLS%..\..\VC\vcvarsall.bat" amd64
  - IF "%platform%" == "x86" CALL "%VS140COMNTOOLS%..\..\VC\vcvarsall.bat" x86
  - npm install -g npm@5
  - npm --version
  - npm install

test_script:
  - npm test

cache:
  # global npm cache
  - '%APPDATA%\\npm-cache'

  # global Yarn cache
  - "%LOCALAPPDATA%\\Yarn"
